apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/saurabh221089/argocd-example-apps.git
    path: guestbook
    targetRevision: HEAD
  destination:
    namespace: guestbook
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      enabled: true
    syncOptions:
      - CreateNamespace=true